### ISSUE TITLE
ResolveError: Couldn't find preset

### ISSUE THREAD

**Issue by rowanwins** [novemberborn/hullabaloo-config-manager#23]
Hi there,

Im trying to introduce ava to a package however I'm running into issues with it pulling in babel presets

The error I'm receiving is 
````
ResolveError: C:\code\mypackage\package.json: Couldn't find preset "transform-es2015-modules-commonjs" relative to directory
    at resolve (C:\code\mypackage\node_modules\hullabaloo-config-manager\lib\resolvePluginsAndPresets.js:111:17)
    at resolvePluginsAndPresets (C:\code\mypackage\node_modules\hullabaloo-config-manager\lib\resolvePluginsAndPresets.js:125:9)
    at reduceChains (C:\code\mypackage\node_modules\hullabaloo-config-manager\lib\reduceChains.js:119:29)
    at new ResolvedConfig (C:\code\mypackage\node_modules\hullabaloo-config-manager\lib\ResolvedConfig.js:12:21)
    at collector.fromConfig.then.chains (C:\code\mypackage\node_modules\hullabaloo-config-manager\index.js:35:21)
````

````
"ava": {
    "require": "babel-register",
    "babel": "inherit"
  },
  "babel": {
    "presets": [
      "transform-es2015-modules-commonjs"
    ]
  },
  "scripts": {
    "avaTest": "ava test/the.test.js"
}
````
No .babelrc files. Running on windows.

I've also tried having the babel config within the ava config but that throws the same error.

Any tips would be great, thanks in advance!

**Comment by rowanwins** [comment]
Doh my bad, I was loading a `plugin` not a `preset`
