### ISSUE TITLE
`Error: Could not find the configuration module for '/foo/.babelrc.js' in the cache`

### ISSUE THREAD

**Issue by vjpr** [novemberborn/hullabaloo-config-manager#29]
I get this message often.

To git rid of it, I have to `rm -rf node_modules/.cache`, then it works for a while. But then I change something (maybe its after installing a new package), and I get this message.

```
  Error: Could not find the configuration module for '/foo/.babelrc.js' in the cache
      at Object.loadCachedModule (/foo/node_modules/.registry.npmjs.org/hullabaloo-config-manager/2.0.0-beta.4/node_modules/hullabaloo-config-manager/build/helpers.js:201:15)
      at defaultOptions (/foo/node_modules/.cache/ava/3f40f9aa425d78e9a8bf2493dee7de25.babel-options.js:9:13)
      at exports.getOptions (/foo/node_modules/.cache/ava/3f40f9aa425d78e9a8bf2493dee7de25.babel-options.js:61:7)
      at CachingPrecompiler.getOptions [as getBabelOptions] (/foo/node_modules/.registry.npmjs.org/ava/1.0.0-beta.4/node_modules/ava/lib/babel-config.js:188:13)
      at CachingPrecompiler._transform (/foo/node_modules/.registry.npmjs.org/ava/1.0.0-beta.4/node_modules/ava/lib/caching-precompiler.js:57:59)
      at transform (/foo/node_modules/.registry.npmjs.org/caching-transform/1.0.1/node_modules/caching-transform/index.js:43:10)
      at CachingPrecompiler.transform (/foo/node_modules/.registry.npmjs.org/caching-transform/1.0.1/node_modules/caching-transform/index.js:60:17)
      at CachingPrecompiler.precompileFile (/foo/node_modules/.registry.npmjs.org/ava/1.0.0-beta.4/node_modules/ava/lib/caching-precompiler.js:36:9)
      at map.files.concat.reduce (/foo/node_modules/.registry.npmjs.org/ava/1.0.0-beta.4/node_modules/ava/api.js:134:51)
      at Array.reduce (<anonymous>)
      at AvaFiles.findTestHelpers.then.helpers (/foo/node_modules/.registry.npmjs.org/ava/1.0.0-beta.4/node_modules/ava/api.js:131:36)
  From previous event:
      at _setupPrecompiler.then.precompilation (/foo/node_modules/.registry.npmjs.org/ava/1.0.0-beta.4/node_modules/ava/api.js:128:83)
      at <anonymous>
```

**Comment by novemberborn** [comment]
This is a bug in AVA itself, see https://github.com/avajs/ava/pull/1788.
